// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLtzZfa97G3tnKpNTUHdZUCScRIM5UmYs',
    appId: '1:474806521329:web:b4fe02612974b7af8a8850',
    messagingSenderId: '474806521329',
    projectId: 'meu-catalogo-ad35e',
    authDomain: 'meu-catalogo-ad35e.firebaseapp.com',
    storageBucket: 'meu-catalogo-ad35e.firebasestorage.app',
    measurementId: 'G-TMTKRSN8W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA_iVHKIIX6NG9pZkl-JN8gTgecONO18g',
    appId: '1:474806521329:android:e727eacdc84d11308a8850',
    messagingSenderId: '474806521329',
    projectId: 'meu-catalogo-ad35e',
    storageBucket: 'meu-catalogo-ad35e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2GVwZHQgrOcSHztabIfrVU07Vkpc4mpY',
    appId: '1:474806521329:ios:bdd7a495fe7a2c518a8850',
    messagingSenderId: '474806521329',
    projectId: 'meu-catalogo-ad35e',
    storageBucket: 'meu-catalogo-ad35e.firebasestorage.app',
    iosBundleId: 'com.example.myCatalog',
  );
}
